trigger:
  branches:
   include:
     - main
  paths:
   include:
     - micro-services/vote/*

pool:
 name: 'My Local Agent' 

resources:
- repo: self

variables:
- group: votingapp-secrets

- name: containerRegistry
  value: Docker Hub Connection

- name: containerRegistryrepository
  value: umerfarooqsyed/voting-app

- name: MicroserviceName
  value: vote

- name: tag
  value: $(Build.BuildId)


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(containerRegistryrepository)'
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/micro-services/vote/Dockerfile'
        tags: '$(tag)'


- stage: Push
  displayName: Push image to Docker Hub
  jobs:
  - job: Push
    displayName: Push image to Docker Hub
    steps:
    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(containerRegistryrepository)'
        command: 'push'
        tags: '$(tag)'

- stage: UpdateManifests
  displayName: Update k8s manifest files
  jobs:
  - job: UpdateManifests
    displayName: Update k8s manifest files
    steps:
    - script: |
        echo "Making script executable"
        chmod +x scripts/update_k8s_manifests.sh

        echo "Running update script for microservice: $(MicroserviceName)"
        ./scripts/update_k8s_manifests.sh $(MicroserviceName)
      displayName: "Update k8s manifest files"


      